name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-17"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "simple-reminder-db"
database_id = "bc7cc58f-63d7-4d5b-9f62-653a55baf7a2"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/10 * * * *"]
